// <auto-generated />
namespace MVCforEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Plus001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Plus001));
        
        string IMigrationMetadata.Id
        {
            get { return "201504010952399_Plus001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
